import ProfilePage from "@/components/ProfilePage"
import profileImg from "./shai-profile.jpg"


// This is the data structure that n8n will populate
const pageData = {
  // Hero Section
  profileImage: profileImg,
  name: "Magic Shai Slagter",
  highlightWord: "Shai",
  tagline: "Exploring the art of automation and AI-powered creativity.",

  // Media Section
  mediaSectionTitle: "Discover The Magic",
  mediaSectionHighlight: "Magic",
  mediaContent: [
    {
      title: "Full Interview",
      type: "video" as const,
      thumbnail: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Full%20Interview-iwCcLEW4xTqhbmxdzyI9ZSoA0MqQrs.png",
      icon: "PlayCircle" as const,
      embedUrl: "https://drive.google.com/file/d/1JH720zgODoaAEmqnmIcNH19HfNl2I3tl/preview",
      description: "Complete interview with Shai Slagter discussing automation and AI",
    },
    {
      title: "Amazing Song",
      type: "audio" as const,
      thumbnail: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Amazing%20Song-6OCYl8ZVL2WbJTtTf5GC9Gd8RQNYDX.png",
      icon: "Music" as const,
      embedUrl: "https://drive.google.com/file/d/18N93E2YlZNsAydBj-ERZ9FsgRhJlpwap/preview",
      description: "Shai's magical musical creation",
    },
    {
      title: "Speaker Introduction",
      type: "video" as const,
      thumbnail: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Introduction-gkDkdqzTCG6Ke9RIwJrWPHmu3hxmtN.png",
      icon: "Mic" as const,
      embedUrl: "https://drive.google.com/file/d/1m5_s0mYUJF8IkLzykxstXPSTF-zO6TBB/preview",
      description: "Introduction to Shai Slagter",
    },
    {
      title: "Interview Highlights",
      type: "videolist" as const,
      thumbnail: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Highlights-QGXKCpPeGGbiuzPUS3LsHLZsPTXrVk.png",
      icon: "Video" as const,
      embedUrl: [
        "https://drive.google.com/file/d/1vxI2X8nfTRhj1beiII2gSpfyuuw2vWa6/preview",
        "https://drive.google.com/file/d/1B_3aj1Us-HbIfE0lDeoY_f7ReQOOiAnQ/preview",
        "https://drive.google.com/file/d/1m0pmxszfJfTpwW-AxgePJ6xFg-ylm39l/preview",
        "https://drive.google.com/file/d/1F5299Jwmwu-5tEwF6NIHnKNB0Tj7d2O2/preview",
        "https://drive.google.com/file/d/1kNSUYAUjiD0R0YRTU6OtplG8-Jx3LlGM/preview",
        "https://drive.google.com/file/d/1OVzXU9iM1iGjv2fKCalB3Gs6ZnjpERYo/preview",
        "https://drive.google.com/file/d/14IPuIXfR0fsy9A5XkBY10KulvNC8Ks4N/preview",
        "https://drive.google.com/file/d/1e3cCR5bDqrdK-1ZTNLPcUB3-0LlDC5ro/preview",
        "https://drive.google.com/file/d/1CNMcLO7xbb1-IV3s3RwN_ItD38ozS4jy/preview",
        "https://drive.google.com/file/d/1hAiw9-cUvxV0r9r4PwjHX7c4fgKg6Hke/preview",
        "https://drive.google.com/file/d/1nVcdXV3w5tsGt3lV-vd2fkJaVgK3L4U9/preview",
        "https://drive.google.com/file/d/1yUg-L0wRgcjglnqYcUU-ha7mjl1HzPVX/preview",
        "https://drive.google.com/file/d/1PixVSn3uyV572qNZRssPOsjNbQLrjhuO/preview",
        "https://drive.google.com/file/d/1LZblz4f7euYrVCLW-MOVqiX7r59ROJ6w/preview",
        "https://drive.google.com/file/d/10Gz9peQYxWoy37pEfQhWx9OmJCO7Oflv/preview",
        "https://drive.google.com/file/d/1IQe9trwYGED_E0wTsqDucWgcN88ZH8C6/preview",
        "https://drive.google.com/file/d/1pFcSp0KebLTCA9Ls9wORC-Z79_K1J88N/preview",
        "https://drive.google.com/file/d/1ziKvesYLI7XQD4BL2lObEbyhMhGkfOGH/preview",
        "https://drive.google.com/file/d/1-S9uB1s2LTsBKVQN4xUoy0vweLWHeJrG/preview",
        "https://drive.google.com/file/d/1gRPk-KuCyN7UDmfCrxumNeSXX8MnbwFw/preview",
        "https://drive.google.com/file/d/1zkK4g5r7gjMLG3C-sO5IIiisDB_NZua-/preview",
        "https://drive.google.com/file/d/1XxbDjGmhoR556FIv70ekSXFUf16xHKii/preview",
        "https://drive.google.com/file/d/1GjdTawPYTCkjpgs4ufRXzBiyjmQjElUT/preview",
        "https://drive.google.com/file/d/1LFAIUcZ_2xw5FQ8KsS_qT4CyqGgP9a2w/preview",
        "https://drive.google.com/file/d/12XoiEcfKNnYnv9DLPjw05GTBxbqTa0_C/preview",
        "https://drive.google.com/file/d/1K3DuzXWcYl12fcKKbv_dp02ziGiz6b3v/preview",
      ],
      description: "Key moments and insights from the interview",
    },
  ],

  // Workflows Section
  workflowSectionTitle: "Automation Workflows",
  workflowSectionHighlight: "Workflows",
  workflows: [
    {
      title: "Property Monitoring Automation",
      nodes: [
        "Trigger",
        "CCTV Feed Node",
        "AI Processing Node",
        "Alert Generation Node",
        "Human Oversight Node",
        "Quality Control Node",
        "Decision Support Node",
        "Notification Node",
        "Reporting Node",
        "Documentation Node",
        "Error Handling Node",
      ],
      description: "This automation sends alerts to human operators based on AI analysis of CCTV footage, allowing for quick response to potential security threats. It reduces the number of false alarms and ensures that operators focus on real issues rather than sifting through irrelevant data.",
    },
    {
      title: "Recruitment Process Automation",
      nodes: [
        "Application Reception Node",
        "AI Resume Screening Node",
        "Human Review Node",
        "Candidate Communication Node",
        "Quality Check Node",
        "Interview Scheduling Node",
        "Feedback Collection Node",
        "Results Compilation Node",
        "Reporting Node",
        "Error Handling Node",
      ],
      description: "This automation streamlines the recruitment process by using AI for initial resume screening while ensuring human involvement for final candidate assessments. It alleviates the issue of AI-sourced candidates lacking authenticity and ensures proper handling of applicant data.",
    },
    {
      title: "Tender Preparation Automation",
      nodes: [
        "Data Compilation Node",
        "AI Analysis Node",
        "Human Review Node",
        "Presentation Creation Node",
        "Feedback Loop Node",
        "Quality Assurance Node",
        "Final Approval Node",
        "Distribution Node",
        "Reminder Node",
        "Error Handling Node",
      ],
      description: "This automation supports the creation of tender documents by collating data and analyzing it using AI, followed by a human review to ensure quality delivery. It addresses potential inaccuracies from solely AI-generated content and retains human expertise in critical documents.",
    },
    {
      title: "Incident Reporting Automation",
      nodes: [
        "Incident Detection Node",
        "Data Aggregation Node",
        "AI Incident Analysis Node",
        "Alert Notification Node",
        "Human Review Node",
        "Decision Support Node",
        "Action Assignment Node",
        "Follow-Up Communication Node",
        "Reporting Node",
        "Quality Control Node",
      ],
      description: "This workflow automates the collection and analysis of incident reports, enabling a quick response to security situations while still engaging human decision-makers. It enhances response times and minimizes the oversight of urgent incidents.",
    },
    {
      title: "Client Communication Automation",
      nodes: [
        "Client Inquiry Node",
        "AI Response Node",
        "Human Validation Node",
        "Personalized Response Node",
        "Quality Verification Node",
        "Follow-Up Node",
        "Case Closure Node",
        "Feedback Request Node",
        "Reporting Node",
        "Error Management Node",
      ],
      description: "This automation manages client communications, using AI to draft initial responses and ensuring human oversight for quality and personalization. It resolves delays in communication and improves client satisfaction through timely responses.",
    },
  ],
  workflowCTAText: "Build the Magic",
  workflowCTAUrl: "https://meet.manymangoes.com/",

  // Highlight titles for videolist
  highlightTitles: [
    "AI's Role: Door Opener, Not Closer, for Business",
    "AI & Human Interaction: Global Salesforce Expertise",
    "AI Time Saver: Boost Client Acquisition & Sales",
    "Apple Sound Secrets: Finding Answers with Tech!",
    "Shai Slagter's Inspiring Journey: Exclusive Interview",
    "Salesforce Marketplace: From Idea to 25 Clients in 4 Weeks!",
    "Salesforce Outreach: Hyper-Targeting for Better Results",
    "Saving Money: Effective Messaging Strategy Explained",
    "Unlock Your Pocket AI: Mate, Your Assistant",
    "Property Monitoring with AI-Powered CCTV Analysis",
    "Recruitment Automation: AI Screening with Human Touch",
    "Tender Preparation: AI Analysis with Expert Review",
    "Incident Response: Automated Detection and Human Decision",
    "Client Communication: AI Draft with Personal Touch",
    "Security Automation: Real-time Threat Detection",
    "HR Process Optimization with AI Assistance",
    "Document Automation: Quality Assured AI Content",
    "Emergency Response: Automated Alert Systems",
    "Customer Service: AI-Enhanced Human Interaction",
    "Business Process Automation: The Future is Here",
    "AI Integration: Balancing Automation and Human Expertise",
    "Smart Security: CCTV Analytics and Alert Systems",
    "Recruitment Revolution: AI Screening Done Right",
    "Tender Success: AI-Powered Document Creation",
    "Incident Management: Automated Response Systems",
    "Communication Excellence: AI-Human Collaboration",
  ],

  // Footer
  footerYear: "2025",
  footerText: "Made with",

  // Optional: Custom accent color
  accentColor: "#F1ab1c",
}

export default function ShaiSlagterPage() {
  return <ProfilePage {...pageData} />
}